<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<!-- Firestore client library -->
		<PackageReference Include="FirebaseAdmin" Version="3.4.0" />
		<PackageReference Include="Google.Apis.Auth" Version="1.71.0" />
		<PackageReference Include="Google.Cloud.Firestore" Version="3.*" />

		<!-- Swagger/Swashbuckle for API docs -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.*" />
	</ItemGroup>

</Project>
